### ISSUE TITLE
Posible crash cuando no se encuentran keypoints

### ISSUE THREAD

**Issue by lsperona** [javierbrk/reconocedordebilletes#2]
Si se intenta hacer una captura con la cámara obstruida, la aplicación se cierra inesperadamente.
La posible causa es no contemplar el caso en el que no se encuentran keypoints.

**Comment by MMoresi** [comment]
@lsperona @MMoresi

**Comment by javierbrk** [comment]
resuelto por  @lsperona  @MMoresi e incorporado por @nanomoretti
