### ISSUE TITLE
Error en Uri del proyecto

### ISSUE THREAD

**Issue by marcosBlasco** [javierbrk/reconocedordebilletes#24]
En la sección "Importar proyectos y vincularlos" que está en la sección desarrollo de la WIKI está el siguiente enlace  "https://github.com/javierbrk"/reconocedordebilletes.git, hay que corregirlo por "https://github.com/javierbrk/reconocedordebilletes.git"

**Comment by ferpucheta** [comment]
@javierbrk ya corregí esta issue
