### ISSUE TITLE
No funciona en Nexus 6P

### ISSUE THREAD

**Issue by ehames** [javierbrk/reconocedordebilletes#9]
Como OpenCV no está linkeada estáticamente, la aplicación no se puede ejecutar en el Nexus 6P.

**Comment by javierbrk** [comment]
el problema fue resuelto parcialmente mediante el uso de librerías incluidas de manera estática. Sin embargo esto acarrea una perdida de performance. Las causas son todavía desconocidas. La solución es utilizar el branch [https://github.com/javierbrk/reconocedordebilletes/tree/staticCVlibs](staticCVlibs)
